/**
 * Enum definition.
 */
const NODE_TYPE = {
  ADV: "Advanced",
  INT: "Intermediate",
  NRM: "Normal"
};

const POPULATION_SIZE = 10,
  VICINITY = 80;

const CWIDTH = 500,
  CHEIGHT = 500,
  SPAWN_BORDER = 70,
  NUMBER_OF_NODES = 100,
  NUMBER_OF_CH = 15,
  NUMBER_OF_SINKS = 1,
  INTERMEDIATE_NODE_FRACTION = 0.1,
  ADVANCED_NODE_FRACTION = 0.2,
  ENERGY_FRACTION_ADVANCED_ALPHA = 2,
  ENERGY_FRACTION_INTERMEDIATE_BETA = 1,
  E_INITIAL_ENERGY = 0.5;
